umd-lib/pcdm-manifests

- .gitignore
- Gemfile
- Gemfile.lock
Use the dot-env gem and a .env file to hold sensitive info for the deployed
application on iiifdev.
https://issues.umd.edu/browse/LIBFCREPO-170
> LIBFCREPO-170. Use dot-env for deployed servers.

- app/controllers/concerns/pcdm2manifest.rb
- config/pcdm2manifest.yml.dist
If present, use them as filenames for client certificate authentication. Also, only send the username and password as HTTP Basic credentials if they are set in the config file.
https://issues.umd.edu/browse/LIBFCREPO-207
> LIBFCREPO-207. Added client_cert and client_key config options.

- app/controllers/concerns/pcdm2manifest.rb
* Removed the description, viewingDirection, and within keys.
* Fixed the template so that the related key gets removed properly.
* Use the first dc:date for the navDate property.
* If present, use dcterms:rightsHolder for attribution.
* If present, use edm:rights for license.
https://issues.umd.edu/browse/LIBFCREPO-176
> LIBFCREPO-176. Clean up manifest metadata.

- app/controllers/concerns/manifest_helper.rb
- app/views/manifests/show.json.jb
- config/application.rb
This ensures compliance with the IIIF Image API spec.
Also fixed a couple other minor issues:
* corrected typo in default manifests URL
* changed logo image URL to point to the https resource on production web server; this will prevent mixed content warnings on pages that embed to Mirador viewer
https://issues.umd.edu/browse/LIBFCREPO-270
> LIBFCREPO-270. Prefix and escape the image identifier.

- app/controllers/manifests_controller.rb
- config/routes.rb
Added a name to the manifest route to get access to the manifest_url and manifest_path helper methods.
https://issues.umd.edu/browse/LIBFCREPO-336
> LIBFCREPO-336. Retain text query when redirecting from page to issue manifest.

- app/controllers/concerns/manifest_helper.rb
- app/controllers/manifests_controller.rb
- app/views/manifests/show.json.jb
The manifest controller will consult those lists when deciding whether to render the manifest or redirect.
Also:
* return empty thumbnail and page sequence if there are no pages, instead of throwing an error
* removed leftover example code from the manifest template.
https://issues.umd.edu/browse/LIBIIIF-57
> LIBIIIF-57. List manifest and canvas components.

- app/controllers/concerns/manifest_helper.rb
- app/controllers/manifests_controller.rb
Added custom exception classes that support a to_h method so that they can be converted to JSON Problem Details responses (see RFC 7807).
https://issues.umd.edu/browse/LIBIIIF-58
> LIBIIIF-58. Respond with HTTP error statuses.

- app/views/manifests/show.json.jb
This adds the citation field to the metadata secion.
Requires that solr is using an updated solconfig.xml that includes the
citation field in the pcdm request handler.
https://issues.umd.edu/browse/LIBIIIF-69
> LIBIIIF-69 Add citation field to manifest metadata

- app/controllers/concerns/manifest_helper.rb
If the display_date Solr field is available, use that, otherwise default to the date field, but strip off the "T00:00:00Z" time section.
https://issues.umd.edu/browse/LIBIIIF-71
> LIBIIIF-71. Use display date in metadata.

- app/controllers/concerns/manifest_helper.rb
- app/views/manifests/show.json.jb
Only attempt to join the bibliographic citation field if it is present.
https://issues.umd.edu/browse/LIBIIIF-75
> LIBIIIF-75. Guard against a nil bibliographic citation field.

- app/controllers/concerns/fcrepo_helper.rb
- app/controllers/concerns/manifest_helper.rb
- app/controllers/manifests_controller.rb
Created an fcrepo_helper module that encapsulates the fcrepo-specific code for generating IIIF manifests. Only the generic code to generate manifests remains in the manifest_helper module.
Additional features:
* Escape slashes when going from path to URI.
* Implement a pairtree-shortening identifier syntax: pcdm/01/23/45/67/01234567-... -> pcdm::01234567-...
https://issues.umd.edu/browse/LIBIIIF-74
> LIBIIIF-74. Separate out fcrepo-specific code.

- lib/iiif/fcrepo.rb
https://issues.umd.edu/browse/LIBIIIF-81
> LIBIIIF-81. Manifest request errors out on missing date.

- lib/iiif/fcrepo.rb
- lib/iiif/fedora2.rb
- lib/iiif_base.rb
* navDate must be a datetime
* added optional description, viewing_direction, and viewing_hint fields
* made nav_date, license, and attribution optional (they only show up if they have a non-null value)
* default metadata value is an empty array
* use the PID as the label for the fedora2 manifests
* include width, height, and format of thumbnails
https://issues.umd.edu/browse/LIBIIIF-78
> LIBIIIF-78. Ensure the manifest is compliant with the IIIF Presentation API.

- lib/iiif_base.rb
Default if the image width or height is not available is 1200. This may result in square thumbnails when there is no dimension metadata on the objects, but that is preferable to broken images.
https://issues.umd.edu/browse/LIBIIIF-80
> LIBIIIF-80. Restore default canvas and image dimensions.

- lib/iiif_base.rb
Restores previous structure that Mirador was expecting.
https://issues.umd.edu/browse/LIBIIIF-89
> LIBIIIF-89. Wrap annotation body resource in an array.

- config/iiif.yml
- lib/iiif/fcrepo.rb
https://issues.umd.edu/browse/LIBIIIF-6
> LIBIIIF-6. For missing fcrepo images, use the "static:unavailable" image.

- config/iiif.yml
- lib/iiif/fedora2.rb
Query the fcrepo Solr core pcdm request handler to try and get the image dimensions for all the images that are part of a given UMDM PID. If this doesn't work, fall back to the old (and slow) way of asking the image server for the info.json for each image. Added a config key for the fedora2 handler, fcrepo_solr_url, that is the URL of the fedora4 core to use. Modified code that queries Solr to assume that the URLs provided in config are to the core, so the application just appends the request handler name.
https://issues.umd.edu/browse/LIBIIIF-90
> LIBIIIF-90. Attempt to get image info for fedora2 PIDs from Solr.

- lib/iiif/fedora2.rb
Ensure that the dmDate key exists before trying to use it.
https://issues.umd.edu/browse/LIBIIIF-96
> LIBIIIF-96. Sanity check when retrieving fedora2 metadata.

- lib/iiif/fedora2.rb
Labels on METS fptr elements are optional, but the current pcdm-manifests code expects them to be there. The fix should be to apply a generic "Page N" label to any canvas where the METS data doesn't have a corresponding label, where N is that canvases 1-based index in the document order.
https://issues.umd.edu/browse/LIBIIIF-99
> LIBIIIF-99 Allow METS item label to be optional

- lib/iiif/fcrepo.rb
https://issues.umd.edu/browse/LIBIIIF-111
> LIBIIIF-111. Added "archival record set" to manifest-level types.

- .env.development
- app/controllers/manifests_controller.rb
- config/application.rb
- config/iiif.yml
- config/initializers/iiif.rb
- lib/iiif/fcrepo.rb
- lib/iiif/fedora2.rb
- modify the solr query
- reverse the canvas and manifest level checks
- anything that is pcdm:Object but not a pcdm:Collection qualifies as a manifest-level resource
- move configuration in the development environment into environment variables
- load IIIF config using an initializer
https://issues.umd.edu/browse/LIBIIIF-114
> LIBIIIF-114. Look for image/* files, not just pcdmuse:PreservationMasterFile.

- lib/iiif/fcrepo.rb
First check the more specific canvas level, then manifest level when determining what manifest id to return for the item. With the adoption of the Item content model, anything that is a canvas will also match the manifest level test.
https://issues.umd.edu/browse/LIBIIIF-124
> LIBIIIF-124. Reverse the manifest level/canvas level check for manifest_id.

- .env.development
- config/iiif.yml
- lib/iiif/fcrepo.rb
- test/lib/iiif/fcrepo_test.rb
- test/test_helper.rb
No longer assumes that there is only a single segment before the pairtree abbreviation.
Also switch the default development environment constants to use localhost servers. This will make it easy to develop against the Docker stack locally.
https://issues.umd.edu/browse/LIBIIIF-130
> LIBIIIF-130. Created a separate Path class to handle fcrepo IIIF id paths.

- .env.development
- app/controllers/manifests_controller.rb
- config/iiif.yml
- lib/iiif/fcrepo.rb
Updated URLs for modified IIIF stack:
* use localhost:8182 for Cantaloupe
* use localhost:3001 for pcdm-manifests (reserves port 3000 for Archelon)
* include context path for fcrepo
* removed the redundant SOLR_URL environment variable
Other general fixes and improvements:
* Standardized the terminology around fcrepo location strings.
* uri: the fully qualified URI to the resource
* path: the full path to the resource inside the repo, without the leading slash
* prefixed: slashes in the full path replaced with colons, and "fcrepo:" prepended
* abbreviated: prefixed form, but with any pairtree sequences replaced with a "::"
* De-duplicated the constants in IIIF::Fcrepo and IIIF::Fcrepo::Item.
* Create a get_subquery_docs() helper method. Encapsulates the difference between how Solr 6 and …
> LIBIIIF-140. Improvements for integrating with Canteloupe Image Server.

- lib/iiif/fcrepo.rb
This fixes the issue of empty annotation lists, since the URI being used to search in Solr was not the correct one.
https://issues.umd.edu/browse/LIBIIIF-157
> LIBIIIF-157. Fix parsing of abbreviated IIIF identifiers for pages.

- lib/iiif/fcrepo.rb
Restores hit highlighting.
https://issues.umd.edu/browse/LIBIIIF-159
> LIBIIIF-159. Fix parsing of abbreviated IIIF identifiers for pages in full-text search.

- .env.development
- .gitignore
- lib/iiif/fcrepo.rb
- lib/iiif_base.rb
* Updated Solr fields in fcrepo handler to use new Solr index structures.
- updated Solr endpoint in the development .env file
* Ignore "/vendor/bundle".
* Get the image dimensions from the IIIF Image server if they are not in the index.
- respect the aspect ratio of thumbnails
- further subdivided the IIIF base methods into smaller self-contained chunks
* Don't abbreviate the IIIF IDs.
- Use the full version of the IIIF ID (without abbreviating the pairtree) so that lookups via the Solr `iiif_manifest__*` fields are easier.
https://umd-dit.atlassian.net/browse/LIBIIIF-179
> LIBIIIF-179. Updated Solr fields in fcrepo handler to use new Solr index structures.

- lib/iiif/fcrepo.rb
- lib/iiif_base.rb
- updated the query to match the new Solr fields
- made the list of OCR fields a module level variable
- refactored the search_hit_list into smaller component methods
- temporarily disabled the textblock list
https://umd-dit.atlassian.net/browse/LIBIIIF-181
> LIBIIIF-181. Full text search with solrizer-creatred index.
